### ISSUE TITLE
Bindings are clearly not thread safe

### ISSUE THREAD

**Issue by Glandos** [yast/yast-python-bindings#2]
When using NetworkInterfaces module, I got a segmentation fault whenever the following code is executed:
https://gist.github.com/Glandos/7cd53ce90d3cce153f64

If you run readIPs in the main thread, there is no problem.
However, I am using this kind of code in a GTK application, and I used to do this kind of lengthy task in a background thread to avoid blocking the UI.

It works on openSuse 11.4, not on openSuse 13.1 (which is using Ruby).

Any ideas? Is it a bug? A feature?

**Comment by dmulder** [comment]
The sample code provided no longer works, and I can't reproduce the described behavior since the bindings rewrite. We can reopen this somebody can show that this is still an issue.
